name: Build

# Controls when the action will run.
on:
  workflow_call:

jobs:
  build:
    # convert this to a matrix if builds differ between platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v4

      # see *py_ver* in ci/update.py
      - name: Setting up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: |
            ci/requirements.txt

      - name: Install dependencies
        shell: sh
        run: |
          [ -d "/c/miniconda" ] && /c/miniconda/condabin/activate.bat
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Build
        run: tox -e build -v

      - name: Upload packages for publishing job
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os }}
          path: |
              dist/*.whl
              dist/*.tar.gz

  publish:
    needs: [build]
    runs-on: 'ubuntu-latest'
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: sh
        run: |
          [ -d "/c/miniconda" ] && /c/miniconda/condabin/activate.bat
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          merge-multiple: true
          path: dist

      - name: Check generated packages
        run: twine check dist/*.*

      - name: Upload packages
        env:
          TWINE_PASSWORD: "${{ secrets.TEST_PYPI_TOKEN }}"
          TWINE_NON_INTERACTIVE: 1
        run: |
          twine upload --disable-progress-bar --skip-existing -u __token__ -r testpypi dist/*.*
