name: Release

# Controls when the action will run.
on:
  workflow_call:

jobs:
  # make a new version first, release or prerelease
  release:
    # Only run this job if new work is pushed to "main"
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git user
        shell: sh
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # see *py_ver* in ci/update.py
      - name: Setting up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: |
            ci/requirements.txt

      - name: Install dependencies
        shell: sh
        run: |
          [ -d "/c/miniconda" ] && /c/miniconda/condabin/activate.bat
          python -m pip install --upgrade pip
          python -m pip install --progress-bar=off -r ci/requirements.txt

      - name: Determine a version number
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: sh
        run: |
          set -x
          NEWVER=$(semantic-release version --print)
          sed -i -e "s/v\([0-9]\+\.\)\{3\}/v$NEWVER./" README.rst
          sed -i -e "s/\([0-9]\+\.\)\{2\}[0-9]\+/$NEWVER/" .cookiecutterrc
          git add README.rst .cookiecutterrc
          # creates a release only if there are relevant changes/commits starting with 'fix/feat()'
          semantic-release version
